version: '3.11'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app  
      - ../data/embeddings/faiss_index:/app/data/embeddings/faiss_index  
    environment:
      - FLASK_ENV=development
    env_file:
      - ../config/.env
